/* ============================================================
   I18N — All UI translations EN/JP/KR/VI/ZH
   File: engjap.js
   ============================================================ */

const translations = {
  "en": {
    "home": "Home",
    "language": "Language",
    "settings": "Settings",
    "players": "Players",
    "rounds": "Rounds",
    "summary": "Summary",
    "fontSize": "Font Size",
    "reset": "Reset",
    "resetAll": "Reset App",
    "resetExcept": "Reset Games",
    "enterCourts": "Enter Number of Courts",
    "importPlayers": "Browse Players ▶",
    "gender": "Gender",
    "male": "Male",
    "female": "Female",
    "import": "Import",
    "enterPlayerName": "Enter Player Name",
    "addPlayer2": "Add",
    "fixedPairs2": "Set Fixed Pairs (Optional)",
    "pround": " Round",
    "nround": "Play ",
    "endrounds": "Finish & Next Round ",
    "endSession": "End Session",
    "roundno": "Round ",
    "roundShort": "R",
    "rank": "Rank",
    "name": "Name",
    "wins": "Wins",
    "played": "Played",
    "rested": "Rested",
    "importExample": "Name,Gender\nKari\nBhavani",
    "Timer": "Timer",
    "min": "min",
    "selectPlayer1": "Select Player 1",
    "selectPlayer2": "Select Player 2",
    "small": "Small",
    "medium": "Medium",
    "large": "Large",
    "maxcourts": "Enter Number of Courts",
    "sittingOut": "Resting",
    "courts": "Courts",
    "theme": "Theme",
    "light": "Light",
    "dark": "Dark",
    "export": "Export",
    "exporthtml": "📄 Export Summary",
    "help": "Help",
    "confirmResetAll": "Do you want to reset everything?",
    "confirmResetGames": "Do you want to reset games only?",
    "endRoundsConfirm": "Do you want to end the rounds?",
    "yes": "Yes",
    "browsePlayersSub": "Select from saved players",
    "statusReady": "Status: Ready",
    "statusProgress": "Status: Progress…",
    "minRounds": "Warm-Up Rounds",
    "roundSettings": "Round Settings",
    "competitive": "Competitive",
    "appTitle": "Sports Club Scheduler",
    "tagline": "Badminton & Pickleball",
    "login": "Login",
    "logout": "Logout",
    "createAccount": "Create Account",
    "claimAccount": "Claim Account",
    "email": "Email",
    "password": "Password",
    "confirmPassword": "Confirm Password",
    "newPassword": "New Password",
    "confirmNewPassword": "Confirm New Password",
    "displayName": "Display Name",
    "recoveryKeyword": "Recovery Keyword",
    "forgotPassword": "Forgot password?",
    "resetPassword": "Reset Password",
    "userId": "User ID",
    "nickname": "Nickname",
    "yourEmail": "Your Email",
    "myCard": "My Card",
    "myClubs": "My Clubs",
    "dashboard": "Dashboard",
    "fixedPairs": "Fixed Pairs",
    "selectPlayers": "Select Players",
    "startRounds": "Start Rounds",
    "watchSession": "Watch Session",
    "viewer": "Viewer",
    "organiser": "Organiser",
    "vault": "Vault",
    "chooseMode": "Choose Mode",
    "howUsingApp": "Choose how you are using the app",
    "watchLive": "Watch live rounds & scores",
    "runSession": "Run session, score games, manage players",
    "clubAdmin": "Club admin — players, requests, management",
    "roundOrganiser": "Round Organiser",
    "vaultManager": "Vault Manager",
    "myClubsTitle": "My Clubs",
    "findClub": "Find a Club",
    "joinClub": "Join",
    "leaveClub": "Leave",
    "noClubSelected": "No club selected",
    "createClub": "Create Club",
    "createNewClub": "Create New Club",
    "createYourClub": "Create Your Club",
    "deleteClub": "Delete Club",
    "connectClub": "Connect",
    "clubManagement": "Club Management",
    "noClubYet": "No club yet — create one to get started",
    "searchClub": "Search Club",
    "findRequest": "Find & request",
    "submitRequest": "Submit Request",
    "requestSent": "Request sent! Waiting for admin approval.",
    "tapConnect": "Tap to connect",
    "register": "Register",
    "modify": "Modify",
    "requests": "Requests",
    "playing": "Playing",
    "onCourtNow": "on court now",
    "pendingApproval": "pending approval",
    "playersInClub": "players in club",
    "tapToEdit": "tap to edit",
    "joinAClub": "join a club",
    "newClub": "new club",
    "removeClub": "remove club",
    "loadingRequests": "Loading requests...",
    "addPlayer": "Add Player",
    "editPlayer": "Edit Player",
    "addRemove": "Add · Remove",
    "alwaysTogether": "Always together",
    "addAtLeast4": "Add at least 4 players",
    "myProfile": "My Profile",
    "recentMatches": "Recent Matches",
    "sessionStats": "Session stats",
    "sessions": "Sessions",
    "allTimeWins": "All-time Wins",
    "allTimeLosses": "All-time Losses",
    "globalRating": "Global Rating",
    "globalPoints": "Global Points",
    "clubRating": "Club Rating",
    "clubPoints": "Club Points",
    "thisWeek": "This Week",
    "thisMonth": "This Month",
    "thisYear": "This Year",
    "signInStats": "Sign in to view your stats",
    "trackStats": "Track your ratings, wins and match history.",
    "appearance": "Appearance",
    "tileStyle": "Tile Style",
    "flat": "Flat",
    "glow": "Glow",
    "color": "Color",
    "subscription": "Subscription",
    "currentMode": "Current Mode",
    "freeTrial": "Free Trial",
    "restorePurchase": "Restore Purchase",
    "subscribeNow": "Subscribe Now",
    "trialEnded": "Your free trial has ended",
    "add": "Add",
    "cancel": "Cancel",
    "save": "Save Changes",
    "clear": "Clear",
    "clearHistory": "Clear History",
    "clearFavorites": "Clear Favorites",
    "delete": "Delete",
    "replace": "Replace",
    "skip": "Skip",
    "start": "Start",
    "end": "End",
    "switch": "Switch",
    "change": "Change",
    "info": "Info",
    "preview": "Preview",
    "loading": "Loading...",
    "liveSessions": "Live sessions",
    "liveNow": "Live Now",
    "noLiveSessions": "No live sessions",
    "favourite": "Favourite",
    "history": "History",
    "whoAreYou": "Who are you?",
    "notSelected": "Not selected",
    "getStarted": "Get Started",
    "welcome": "Welcome",
    "selectFromSaved": "Select from saved players",
    "selectNameProfile": "Select your name to personalise your profile",
    "asRegisteredByAdmin": "as registered by admin",
    "givenByAdmin": "given by admin",
    "minSixChars": "min 6 characters",
    "toResetPassword": "to reset password if forgotten",
    "yourNameAlias": "your name or alias",
    "defaultPassword": "Default Password",
    "tile": "Tile",
    "wideTile": "Wide Tile",
    "description": "Description",
    "roundOrganiserDesc": "Run session, score games, manage players",
    "vaultManagerDesc": "Club admin — players, requests, management",
    "watchLiveDesc": "Watch live rounds & scores",
    "startRoundsBtn": "Start Rounds ›",
    "goBtn": "Go ›",
    "helpGuide": "Help & Guide",
    "findAClub": "Find a Club",
    "addPlayers": "Add Players",
    "player1": "Player 1",
    "player2": "Player 2",
    "editPlayerName": "Edit player name",
    "removePlayer": "Remove player",
    "connectToClub": "Connect to Club",
    "selectClub": "— Select club —",
    "nextRound": "Next Round",
    "markWinner": "Mark winner",
    "markAllWinners": "Please mark winners for all games",
    "inProgress": "In Progress",
    "lockBtn": "Lock",
    "unlockBtn": "Unlock",
    "playingNow": "Playing Now",
    "registerPlayers": "Register Players",
    "modifyPlayers": "Modify Players",
    "joinRequests": "Join Requests",
    "userID": "User ID",
    "passwordBlank": "Password (leave blank to keep)",
    "selectClubDelete": "— Select club to delete —",
    "refresh": "↻ Refresh",
    "sync": "↻ Sync",
    "adminBadge": "ADMIN",
    "userBadge": "USER",
    "viewerBadge": "VIEWER",
    "liveBadge": "LIVE",
    "newBadge": "NEW",
    "readyBadge": "READY",
    "welcomeTitle": "Welcome",
    "verifyEmail": "Verify Email",
    "resendCode": "Resend Code",
    "findYourClub": "Find Your Club",
    "resetRoundsOnly": "Reset Rounds Only",
    "resting": "Resting",
    "round": "Round",
    "court": "Court",
    "howUsingAppToday": "How are you using the app today?",
    "claimMyAccount": "Claim My Account",
    "clearBtn": "Clear",
    "clubLabel": "Club",
    "clubRatingLabel": "Club Rating",
    "globalRatingLabel": "Global Rating",
    "clubSchedulerPro": "Club Scheduler Pro",
    "courtsLabel": "Courts",
    "emailLabel": "Email",
    "endBtn": "End",
    "favouriteBtn": "Favourite",
    "joinBtn": "Join",
    "lessOneShuttle": "Less than one shuttle per year",
    "pairsLabel": "Pairs",
    "passwordLabel": "Password",
    "replaceBtn": "Replace",
    "roundsLabel": "Rounds",
    "saveSet": "Save Set",
    "searchByClubName": "Search by club name and request to join",
    "skipBtn": "Skip",
    "startBtn": "Start",
    "switchBtn": "Switch",
    "useAdminMode": "Use Vault mode for full admin access.",
    "selectClubOption": "— Select club —",
    "loadingClubs": "— Loading clubs… —",
    "adminAccess": "Admin Access",
    "connectToClubBadminton": "🏸 Connect to Club",
    "browseBtn": "Browse",
    "sessionStatsLabel": "Session stats",
    "summaryLabel": "Summary",
    "subFeature1": "✓ Full stats & session history",
    "subFeature2": "✓ Live rounds & scoring",
    "subFeature3": "✓ Organiser mode — run sessions",
    "subFeature4": "✓ Players & Fixed Pairs management",
    "subFeature5": "✓ Viewer mode — watch live scores",
    "backHome": "‹ Home",
    "notConnected": "Not connected",
    "setupBadge": "SETUP",
    "memberMsg": "You are a member of this club."
  },
  "jp": {
    "home": "ホーム",
    "players": "選手一覧",
    "rounds": "試合ラウンド",
    "summary": "集計",
    "language": "言語",
    "fontSize": "文字サイズ",
    "reset": "リセット",
    "resetAll": "全てをリセット",
    "resetExcept": "プレーヤー以外をリセット",
    "enterCourts": "コート数を入力",
    "importPlayers": "プレイヤーを閲覧 ▶",
    "gender": "性別",
    "male": "男",
    "female": "女",
    "import": "取り込み",
    "enterPlayerName": "選手名を入力",
    "fixedPairs2": "固定ペア設定（任意）",
    "pround": " ラウンド",
    "nround": "ラウンド開始 ",
    "endrounds": "終了して次のラウンド ",
    "endSession": "セッション終了",
    "roundno": "ラウンド ",
    "roundShort": "R",
    "rank": "順位",
    "name": "名前",
    "wins": "勝利",
    "played": "試合数",
    "rested": "休憩数",
    "importExample": "名前,性別\nカリ\nババニ",
    "Timer": "タイマー",
    "min": "分",
    "selectPlayer1": "プレーヤー1を選択",
    "selectPlayer2": "プレーヤー2を選択",
    "small": "小",
    "medium": "中",
    "large": "大",
    "maxcourts": "コートの数を入力してください",
    "sittingOut": "休憩中:",
    "courts": "コート",
    "theme": "テーマ",
    "light": "ライト",
    "dark": "ダーク",
    "export": "エクスポート",
    "exporthtml": "📄 概要出力",
    "confirmResetAll": "すべてをリセットしますか？",
    "confirmResetGames": "試合のみをリセットしますか？",
    "endRoundsConfirm": "ラウンドを終了しますか？",
    "yes": "はい",
    "help": "ヘルプ",
    "statusReady": "状態: 準備完了",
    "statusProgress": "状態: 進行中...",
    "minRounds": "ウォームアップラウンド",
    "roundSettings": "ラウンド設定",
    "competitive": "競技モード",
    "browsePlayersSub": "保存済みプレイヤーから選択",
    "appTitle": "スポーツクラブスケジューラー",
    "tagline": "バドミントン＆ピックルボール",
    "login": "ログイン",
    "logout": "ログアウト",
    "createAccount": "アカウント作成",
    "claimAccount": "アカウント申請",
    "email": "メール",
    "password": "パスワード",
    "confirmPassword": "パスワード確認",
    "newPassword": "新しいパスワード",
    "confirmNewPassword": "新しいパスワード確認",
    "displayName": "表示名",
    "recoveryKeyword": "回復キーワード",
    "forgotPassword": "パスワードを忘れた方",
    "resetPassword": "パスワードリセット",
    "userId": "ユーザーID",
    "nickname": "ニックネーム",
    "yourEmail": "あなたのメール",
    "myCard": "マイカード",
    "myClubs": "マイクラブ",
    "dashboard": "ダッシュボード",
    "fixedPairs": "固定ペア",
    "selectPlayers": "選手を選択",
    "startRounds": "ラウンド開始",
    "watchSession": "セッション観戦",
    "viewer": "観戦者",
    "organiser": "オーガナイザー",
    "vault": "ヴォールト",
    "chooseMode": "モードを選択",
    "howUsingApp": "アプリの使い方を選択してください",
    "watchLive": "ライブラウンド＆スコアを観戦",
    "runSession": "セッション運営・スコア管理・選手管理",
    "clubAdmin": "クラブ管理・選手・リクエスト",
    "roundOrganiser": "ラウンドオーガナイザー",
    "vaultManager": "ヴォールトマネージャー",
    "myClubsTitle": "マイクラブ",
    "findClub": "クラブを検索",
    "joinClub": "参加",
    "leaveClub": "退会",
    "noClubSelected": "クラブ未選択",
    "createClub": "クラブ作成",
    "createNewClub": "新しいクラブを作成",
    "createYourClub": "クラブを作成する",
    "deleteClub": "クラブ削除",
    "connectClub": "接続",
    "clubManagement": "クラブ管理",
    "noClubYet": "クラブがありません。作成してください",
    "searchClub": "クラブ検索",
    "findRequest": "検索・申請",
    "submitRequest": "申請を送信",
    "requestSent": "申請を送信しました。管理者の承認をお待ちください。",
    "tapConnect": "タップして接続",
    "register": "登録",
    "modify": "変更",
    "requests": "リクエスト",
    "playing": "試合中",
    "onCourtNow": "現在試合中",
    "pendingApproval": "承認待ち",
    "playersInClub": "クラブ内選手",
    "tapToEdit": "タップして編集",
    "joinAClub": "クラブに参加",
    "newClub": "新しいクラブ",
    "removeClub": "クラブを削除",
    "loadingRequests": "リクエストを読み込み中...",
    "addPlayer": "選手を追加",
    "editPlayer": "選手を編集",
    "addRemove": "追加・削除",
    "alwaysTogether": "常にペア",
    "addAtLeast4": "4人以上追加してください",
    "myProfile": "マイプロフィール",
    "recentMatches": "最近の試合",
    "sessionStats": "セッション統計",
    "sessions": "セッション",
    "allTimeWins": "総勝利数",
    "allTimeLosses": "総敗北数",
    "globalRating": "グローバルレーティング",
    "globalPoints": "グローバルポイント",
    "clubRating": "クラブレーティング",
    "clubPoints": "クラブポイント",
    "thisWeek": "今週",
    "thisMonth": "今月",
    "thisYear": "今年",
    "signInStats": "統計を見るにはサインインしてください",
    "trackStats": "レーティング・勝利・試合履歴を追跡",
    "appearance": "外観",
    "tileStyle": "タイルスタイル",
    "flat": "フラット",
    "glow": "グロー",
    "color": "カラー",
    "subscription": "サブスクリプション",
    "currentMode": "現在のモード",
    "freeTrial": "無料トライアル",
    "restorePurchase": "購入を復元",
    "subscribeNow": "今すぐ購読",
    "trialEnded": "無料トライアルが終了しました",
    "add": "追加",
    "cancel": "キャンセル",
    "save": "変更を保存",
    "clear": "クリア",
    "clearHistory": "履歴をクリア",
    "clearFavorites": "お気に入りをクリア",
    "delete": "削除",
    "replace": "置換",
    "skip": "スキップ",
    "start": "開始",
    "end": "終了",
    "switch": "切替",
    "change": "変更",
    "info": "情報",
    "preview": "プレビュー",
    "loading": "読み込み中...",
    "liveSessions": "ライブセッション",
    "liveNow": "現在ライブ中",
    "noLiveSessions": "ライブセッションなし",
    "favourite": "お気に入り",
    "history": "履歴",
    "whoAreYou": "あなたは誰ですか？",
    "notSelected": "未選択",
    "getStarted": "始める",
    "welcome": "ようこそ",
    "selectFromSaved": "保存済みから選択",
    "selectNameProfile": "プロフィール設定のために名前を選択",
    "asRegisteredByAdmin": "管理者が登録した名前",
    "givenByAdmin": "管理者から提供",
    "minSixChars": "6文字以上",
    "toResetPassword": "パスワードリセット用",
    "yourNameAlias": "あなたの名前またはニックネーム",
    "defaultPassword": "デフォルトパスワード",
    "tile": "タイル",
    "wideTile": "ワイドタイル",
    "description": "説明",
    "addPlayer2": "追加",
    "addPlayers": "選手を追加",
    "adminAccess": "管理者アクセス",
    "adminBadge": "ADMIN",
    "backHome": "‹ ホーム",
    "browseBtn": "参照",
    "claimMyAccount": "アカウントを申請",
    "clearBtn": "クリア",
    "clubLabel": "クラブ",
    "clubRatingLabel": "クラブレーティング",
    "clubSchedulerPro": "CLUB Scheduler Pro",
    "connectToClub": "クラブに接続",
    "connectToClubBadminton": "🏸 クラブに接続",
    "court": "コート",
    "courtsLabel": "コート",
    "editPlayerName": "選手名を編集",
    "emailLabel": "メール",
    "endBtn": "終了",
    "favouriteBtn": "お気に入り",
    "findAClub": "クラブを探す",
    "findYourClub": "クラブを見つける",
    "globalRatingLabel": "グローバルレーティング",
    "goBtn": "開始 ›",
    "helpGuide": "ヘルプ＆ガイド",
    "howUsingAppToday": "今日はどのようにアプリを使用しますか？",
    "inProgress": "進行中",
    "joinBtn": "参加",
    "joinRequests": "参加リクエスト",
    "lessOneShuttle": "年間シャトル1個未満",
    "liveBadge": "LIVE",
    "loadingClubs": "— クラブを読み込み中… —",
    "lockBtn": "ロック",
    "markAllWinners": "全試合の勝者をマークしてください",
    "markWinner": "勝者をマーク",
    "modifyPlayers": "選手を変更",
    "newBadge": "NEW",
    "nextRound": "次のラウンド",
    "pairsLabel": "ペア",
    "passwordBlank": "パスワード（変更しない場合は空白）",
    "passwordLabel": "パスワード",
    "player1": "プレーヤー1",
    "player2": "プレーヤー2",
    "playingNow": "現在試合中",
    "readyBadge": "READY",
    "refresh": "↻ 更新",
    "registerPlayers": "選手を登録",
    "removePlayer": "選手を削除",
    "replaceBtn": "置換",
    "resendCode": "コードを再送信",
    "resetRoundsOnly": "ラウンドのみリセット",
    "resting": "休憩中",
    "round": "ラウンド",
    "roundOrganiserDesc": "セッション運営・スコア管理・選手管理",
    "roundsLabel": "ラウンド",
    "saveSet": "セットを保存",
    "searchByClubName": "クラブ名で検索してリクエスト",
    "selectClub": "— クラブを選択 —",
    "selectClubDelete": "— 削除するクラブを選択 —",
    "selectClubOption": "— クラブを選択 —",
    "sessionStatsLabel": "セッション統計",
    "settings": "設定",
    "skipBtn": "スキップ",
    "startBtn": "開始",
    "startRoundsBtn": "ラウンド開始 ›",
    "subFeature1": "✓ 完全な統計とセッション履歴",
    "subFeature2": "✓ ライブラウンドとスコアリング",
    "subFeature3": "✓ オーガナイザーモード — セッション運営",
    "subFeature4": "✓ 選手と固定ペア管理",
    "subFeature5": "✓ 観戦者モード — ライブスコア観戦",
    "summaryLabel": "集計",
    "switchBtn": "切替",
    "sync": "↻ 同期",
    "unlockBtn": "ロック解除",
    "useAdminMode": "Vaultモードで完全な管理アクセスを利用",
    "userBadge": "USER",
    "userID": "ユーザーID",
    "vaultManagerDesc": "クラブ管理・選手・リクエスト",
    "verifyEmail": "メールを認証",
    "viewerBadge": "VIEWER",
    "watchLiveDesc": "ライブラウンド＆スコアを観戦",
    "welcomeTitle": "ようこそ",
    "notConnected": "未接続",
    "setupBadge": "SETUP",
    "memberMsg": "このクラブのメンバーです。"
  },
  "kr": {
    "home": "홈",
    "players": "선수",
    "rounds": "라운드",
    "summary": "요약",
    "language": "언어",
    "fontSize": "글자 크기",
    "reset": "초기화",
    "resetAll": "전체 초기화",
    "resetExcept": "경기만 초기화",
    "enterCourts": "코트 수 입력",
    "importPlayers": "플레이어 찾아보기 ▶",
    "gender": "성별",
    "male": "남성",
    "female": "여성",
    "import": "가져오기",
    "enterPlayerName": "선수 이름 입력",
    "fixedPairs2": "고정 페어 설정 (선택)",
    "pround": " 라운드",
    "nround": "라운드 시작 ",
    "endrounds": "종료 및 다음 라운드 ",
    "endSession": "세션 종료",
    "roundno": "라운드 ",
    "roundShort": "R",
    "rank": "순위",
    "name": "이름",
    "wins": "승리",
    "played": "경기 수",
    "rested": "휴식 수",
    "importExample": "이름,성별\n카리\n바바니",
    "Timer": "타이머",
    "min": "분",
    "selectPlayer1": "선수 1 선택",
    "selectPlayer2": "선수 2 선택",
    "small": "작게",
    "medium": "보통",
    "large": "크게",
    "maxcourts": "코트 수를 입력하세요",
    "sittingOut": "휴식 중:",
    "courts": "코트",
    "theme": "테마",
    "light": "라이트",
    "dark": "다크",
    "export": "내보내기",
    "exporthtml": "📄 요약 내보내기",
    "confirmResetAll": "모든 데이터를 초기화하시겠습니까?",
    "confirmResetGames": "경기만 초기화하시겠습니까?",
    "endRoundsConfirm": "라운드를 종료하시겠습니까?",
    "yes": "확인",
    "help": "도움말",
    "statusReady": "상태: 준비 완료",
    "statusProgress": "상태: 진행 중…",
    "minRounds": "워밍업 라운드",
    "roundSettings": "라운드 설정",
    "competitive": "경쟁 모드",
    "browsePlayersSub": "저장된 선수에서 선택",
    "appTitle": "스포츠 클럽 스케줄러",
    "tagline": "배드민턴 & 피클볼",
    "login": "로그인",
    "logout": "로그아웃",
    "createAccount": "계정 만들기",
    "claimAccount": "계정 신청",
    "email": "이메일",
    "password": "비밀번호",
    "confirmPassword": "비밀번호 확인",
    "newPassword": "새 비밀번호",
    "confirmNewPassword": "새 비밀번호 확인",
    "displayName": "표시 이름",
    "recoveryKeyword": "복구 키워드",
    "forgotPassword": "비밀번호 찾기",
    "resetPassword": "비밀번호 재설정",
    "userId": "사용자 ID",
    "nickname": "닉네임",
    "yourEmail": "이메일 주소",
    "myCard": "내 카드",
    "myClubs": "내 클럽",
    "dashboard": "대시보드",
    "fixedPairs": "고정 페어",
    "selectPlayers": "선수 선택",
    "startRounds": "라운드 시작",
    "watchSession": "세션 관전",
    "viewer": "관전자",
    "organiser": "주최자",
    "vault": "볼트",
    "chooseMode": "모드 선택",
    "howUsingApp": "앱 사용 방법을 선택하세요",
    "watchLive": "라이브 라운드 & 점수 관전",
    "runSession": "세션 운영, 게임 점수, 선수 관리",
    "clubAdmin": "클럽 관리 — 선수, 요청, 관리",
    "roundOrganiser": "라운드 주최자",
    "vaultManager": "볼트 매니저",
    "myClubsTitle": "내 클럽",
    "findClub": "클럽 찾기",
    "joinClub": "참여",
    "leaveClub": "탈퇴",
    "noClubSelected": "클럽 미선택",
    "createClub": "클럽 만들기",
    "createNewClub": "새 클럽 만들기",
    "createYourClub": "클럽을 만드세요",
    "deleteClub": "클럽 삭제",
    "connectClub": "연결",
    "clubManagement": "클럽 관리",
    "noClubYet": "클럽이 없습니다. 만들어 보세요",
    "searchClub": "클럽 검색",
    "findRequest": "검색 & 요청",
    "submitRequest": "요청 제출",
    "requestSent": "요청이 전송되었습니다. 관리자 승인을 기다려 주세요.",
    "tapConnect": "탭하여 연결",
    "register": "등록",
    "modify": "수정",
    "requests": "요청",
    "playing": "경기 중",
    "onCourtNow": "현재 경기 중",
    "pendingApproval": "승인 대기 중",
    "playersInClub": "클럽 선수",
    "tapToEdit": "탭하여 편집",
    "joinAClub": "클럽 참여",
    "newClub": "새 클럽",
    "removeClub": "클럽 제거",
    "loadingRequests": "요청 불러오는 중...",
    "addPlayer": "선수 추가",
    "editPlayer": "선수 편집",
    "addRemove": "추가 · 제거",
    "alwaysTogether": "항상 함께",
    "addAtLeast4": "4명 이상 추가하세요",
    "myProfile": "내 프로필",
    "recentMatches": "최근 경기",
    "sessionStats": "세션 통계",
    "sessions": "세션",
    "allTimeWins": "전체 승리",
    "allTimeLosses": "전체 패배",
    "globalRating": "글로벌 레이팅",
    "globalPoints": "글로벌 포인트",
    "clubRating": "클럽 레이팅",
    "clubPoints": "클럽 포인트",
    "thisWeek": "이번 주",
    "thisMonth": "이번 달",
    "thisYear": "올해",
    "signInStats": "통계를 보려면 로그인하세요",
    "trackStats": "레이팅, 승리 및 경기 기록 추적",
    "appearance": "외관",
    "tileStyle": "타일 스타일",
    "flat": "플랫",
    "glow": "글로우",
    "color": "컬러",
    "subscription": "구독",
    "currentMode": "현재 모드",
    "freeTrial": "무료 체험",
    "restorePurchase": "구매 복원",
    "subscribeNow": "지금 구독",
    "trialEnded": "무료 체험이 종료되었습니다",
    "add": "추가",
    "cancel": "취소",
    "save": "변경 저장",
    "clear": "지우기",
    "clearHistory": "기록 지우기",
    "clearFavorites": "즐겨찾기 지우기",
    "delete": "삭제",
    "replace": "교체",
    "skip": "건너뛰기",
    "start": "시작",
    "end": "종료",
    "switch": "전환",
    "change": "변경",
    "info": "정보",
    "preview": "미리보기",
    "loading": "불러오는 중...",
    "liveSessions": "라이브 세션",
    "liveNow": "현재 라이브",
    "noLiveSessions": "라이브 세션 없음",
    "favourite": "즐겨찾기",
    "history": "기록",
    "whoAreYou": "당신은 누구인가요?",
    "notSelected": "미선택",
    "getStarted": "시작하기",
    "welcome": "환영합니다",
    "selectFromSaved": "저장된 선수에서 선택",
    "selectNameProfile": "프로필 설정을 위해 이름을 선택하세요",
    "asRegisteredByAdmin": "관리자가 등록한 이름",
    "givenByAdmin": "관리자 제공",
    "minSixChars": "최소 6자",
    "toResetPassword": "비밀번호 재설정용",
    "yourNameAlias": "이름 또는 별명",
    "defaultPassword": "기본 비밀번호",
    "tile": "타일",
    "wideTile": "와이드 타일",
    "description": "설명",
    "addPlayer2": "추가",
    "addPlayers": "선수 추가",
    "adminAccess": "관리자 액세스",
    "adminBadge": "ADMIN",
    "backHome": "‹ 홈",
    "browseBtn": "찾아보기",
    "claimMyAccount": "계정 신청",
    "clearBtn": "지우기",
    "clubLabel": "클럽",
    "clubRatingLabel": "클럽 레이팅",
    "clubSchedulerPro": "CLUB Scheduler Pro",
    "connectToClub": "클럽 연결",
    "connectToClubBadminton": "🏸 클럽 연결",
    "court": "코트",
    "courtsLabel": "코트",
    "editPlayerName": "선수 이름 편집",
    "emailLabel": "이메일",
    "endBtn": "종료",
    "favouriteBtn": "즐겨찾기",
    "findAClub": "클럽 찾기",
    "findYourClub": "클럽 찾기",
    "globalRatingLabel": "글로벌 레이팅",
    "goBtn": "시작 ›",
    "helpGuide": "도움말 및 가이드",
    "howUsingAppToday": "오늘 앱을 어떻게 사용하시겠습니까?",
    "inProgress": "진행 중",
    "joinBtn": "참여",
    "joinRequests": "참여 요청",
    "lessOneShuttle": "연간 셔틀콕 1개 미만",
    "liveBadge": "LIVE",
    "loadingClubs": "— 클럽 불러오는 중… —",
    "lockBtn": "잠금",
    "markAllWinners": "모든 경기의 승자를 표시해 주세요",
    "markWinner": "승자 표시",
    "modifyPlayers": "선수 수정",
    "newBadge": "NEW",
    "nextRound": "다음 라운드",
    "pairsLabel": "페어",
    "passwordBlank": "비밀번호 (변경 없으면 공백)",
    "passwordLabel": "비밀번호",
    "player1": "선수 1",
    "player2": "선수 2",
    "playingNow": "현재 경기 중",
    "readyBadge": "READY",
    "refresh": "↻ 새로고침",
    "registerPlayers": "선수 등록",
    "removePlayer": "선수 삭제",
    "replaceBtn": "교체",
    "resendCode": "코드 재전송",
    "resetRoundsOnly": "라운드만 초기화",
    "resting": "휴식 중",
    "round": "라운드",
    "roundOrganiserDesc": "세션 운영, 게임 점수, 선수 관리",
    "roundsLabel": "라운드",
    "saveSet": "세트 저장",
    "searchByClubName": "클럽 이름으로 검색 및 요청",
    "selectClub": "— 클럽 선택 —",
    "selectClubDelete": "— 삭제할 클럽 선택 —",
    "selectClubOption": "— 클럽 선택 —",
    "sessionStatsLabel": "세션 통계",
    "settings": "설정",
    "skipBtn": "건너뛰기",
    "startBtn": "시작",
    "startRoundsBtn": "라운드 시작 ›",
    "subFeature1": "✓ 완전한 통계 및 세션 기록",
    "subFeature2": "✓ 라이브 라운드 및 점수",
    "subFeature3": "✓ 주최자 모드 — 세션 운영",
    "subFeature4": "✓ 선수 및 고정 페어 관리",
    "subFeature5": "✓ 관전자 모드 — 라이브 점수 관전",
    "summaryLabel": "요약",
    "switchBtn": "전환",
    "sync": "↻ 동기화",
    "unlockBtn": "잠금 해제",
    "useAdminMode": "Vault 모드로 전체 관리 액세스 사용",
    "userBadge": "USER",
    "userID": "사용자 ID",
    "vaultManagerDesc": "클럽 관리 — 선수, 요청, 관리",
    "verifyEmail": "이메일 인증",
    "viewerBadge": "VIEWER",
    "watchLiveDesc": "라이브 라운드 & 점수 관전",
    "welcomeTitle": "환영합니다",
    "notConnected": "연결되지 않음",
    "setupBadge": "SETUP",
    "memberMsg": "이 클럽의 회원입니다."
  },
  "vi": {
    "home": "Trang chủ",
    "players": "Người chơi",
    "rounds": "Vòng đấu",
    "summary": "Tóm tắt",
    "language": "Ngôn ngữ",
    "fontSize": "Cỡ chữ",
    "reset": "Đặt lại",
    "resetAll": "Đặt lại tất cả",
    "resetExcept": "Đặt lại trận đấu",
    "enterCourts": "Nhập số sân",
    "importPlayers": "Duyệt người chơi ▶",
    "gender": "Giới tính",
    "male": "Nam",
    "female": "Nữ",
    "import": "Nhập",
    "enterPlayerName": "Nhập tên người chơi",
    "fixedPairs2": "Cố định cặp đấu (Tùy chọn)",
    "pround": " Vòng",
    "nround": "Bắt đầu vòng ",
    "endrounds": "Kết thúc & Vòng tiếp theo ",
    "endSession": "Kết thúc phiên",
    "roundno": "Vòng ",
    "roundShort": "R",
    "rank": "Xếp hạng",
    "name": "Tên",
    "wins": "Chiến thắng",
    "played": "Số trận",
    "rested": "Số lần nghỉ",
    "importExample": "Tên,Giới tính\nKari\nBhavani",
    "Timer": "Hẹn giờ",
    "min": "phút",
    "selectPlayer1": "Chọn người chơi 1",
    "selectPlayer2": "Chọn người chơi 2",
    "small": "Nhỏ",
    "medium": "Vừa",
    "large": "Lớn",
    "maxcourts": "Nhập số sân",
    "sittingOut": "Đang nghỉ:",
    "courts": "Sân",
    "theme": "Chủ đề",
    "light": "Sáng",
    "dark": "Tối",
    "export": "Xuất",
    "exporthtml": "📄 Xuất bản tóm tắt",
    "confirmResetAll": "Bạn có muốn đặt lại tất cả không?",
    "confirmResetGames": "Bạn có muốn đặt lại trận đấu không?",
    "endRoundsConfirm": "Bạn có muốn kết thúc các vòng không?",
    "yes": "Có",
    "help": "Trợ giúp",
    "statusReady": "Trạng thái: Sẵn sàng",
    "statusProgress": "Trạng thái: Đang tiến hành…",
    "minRounds": "Vòng khởi động",
    "roundSettings": "Cài đặt vòng",
    "competitive": "Cạnh tranh",
    "browsePlayersSub": "Chọn từ danh sách đã lưu",
    "appTitle": "Lịch Trình Câu Lạc Bộ Thể Thao",
    "tagline": "Cầu Lông & Pickleball",
    "login": "Đăng Nhập",
    "logout": "Đăng Xuất",
    "createAccount": "Tạo Tài Khoản",
    "claimAccount": "Xác Nhận Tài Khoản",
    "email": "Email",
    "password": "Mật Khẩu",
    "confirmPassword": "Xác Nhận Mật Khẩu",
    "newPassword": "Mật Khẩu Mới",
    "confirmNewPassword": "Xác Nhận Mật Khẩu Mới",
    "displayName": "Tên Hiển Thị",
    "recoveryKeyword": "Từ Khóa Khôi Phục",
    "forgotPassword": "Quên mật khẩu?",
    "resetPassword": "Đặt Lại Mật Khẩu",
    "userId": "ID Người Dùng",
    "nickname": "Biệt Danh",
    "yourEmail": "Email Của Bạn",
    "myCard": "Thẻ Của Tôi",
    "myClubs": "CLB Của Tôi",
    "dashboard": "Bảng Điều Khiển",
    "fixedPairs": "Cặp Cố Định",
    "selectPlayers": "Chọn Người Chơi",
    "startRounds": "Bắt Đầu Vòng",
    "watchSession": "Xem Phiên",
    "viewer": "Khán Giả",
    "organiser": "Người Tổ Chức",
    "vault": "Kho",
    "chooseMode": "Chọn Chế Độ",
    "howUsingApp": "Chọn cách bạn sử dụng ứng dụng",
    "watchLive": "Xem vòng đấu & điểm số trực tiếp",
    "runSession": "Điều hành phiên, tính điểm, quản lý người chơi",
    "clubAdmin": "Quản trị CLB — người chơi, yêu cầu, quản lý",
    "roundOrganiser": "Người Tổ Chức Vòng",
    "vaultManager": "Quản Lý Kho",
    "myClubsTitle": "CLB Của Tôi",
    "findClub": "Tìm CLB",
    "joinClub": "Tham Gia",
    "leaveClub": "Rời",
    "noClubSelected": "Chưa chọn CLB",
    "createClub": "Tạo CLB",
    "createNewClub": "Tạo CLB Mới",
    "createYourClub": "Tạo CLB Của Bạn",
    "deleteClub": "Xóa CLB",
    "connectClub": "Kết Nối",
    "clubManagement": "Quản Lý CLB",
    "noClubYet": "Chưa có CLB. Tạo một CLB để bắt đầu",
    "searchClub": "Tìm Kiếm CLB",
    "findRequest": "Tìm & yêu cầu",
    "submitRequest": "Gửi Yêu Cầu",
    "requestSent": "Đã gửi yêu cầu! Chờ admin phê duyệt.",
    "tapConnect": "Nhấn để kết nối",
    "register": "Đăng Ký",
    "modify": "Sửa Đổi",
    "requests": "Yêu Cầu",
    "playing": "Đang Chơi",
    "onCourtNow": "đang trên sân",
    "pendingApproval": "chờ phê duyệt",
    "playersInClub": "người chơi trong CLB",
    "tapToEdit": "nhấn để chỉnh sửa",
    "joinAClub": "tham gia CLB",
    "newClub": "CLB mới",
    "removeClub": "xóa CLB",
    "loadingRequests": "Đang tải yêu cầu...",
    "addPlayer": "Thêm Người Chơi",
    "editPlayer": "Chỉnh Sửa Người Chơi",
    "addRemove": "Thêm · Xóa",
    "alwaysTogether": "Luôn cùng nhau",
    "addAtLeast4": "Thêm ít nhất 4 người chơi",
    "myProfile": "Hồ Sơ Của Tôi",
    "recentMatches": "Trận Đấu Gần Đây",
    "sessionStats": "Thống Kê Phiên",
    "sessions": "Phiên",
    "allTimeWins": "Tổng Thắng",
    "allTimeLosses": "Tổng Thua",
    "globalRating": "Xếp Hạng Toàn Cầu",
    "globalPoints": "Điểm Toàn Cầu",
    "clubRating": "Xếp Hạng CLB",
    "clubPoints": "Điểm CLB",
    "thisWeek": "Tuần Này",
    "thisMonth": "Tháng Này",
    "thisYear": "Năm Nay",
    "signInStats": "Đăng nhập để xem thống kê",
    "trackStats": "Theo dõi xếp hạng, thắng và lịch sử trận đấu.",
    "appearance": "Giao Diện",
    "tileStyle": "Kiểu Ô",
    "flat": "Phẳng",
    "glow": "Phát Sáng",
    "color": "Màu Sắc",
    "subscription": "Đăng Ký",
    "currentMode": "Chế Độ Hiện Tại",
    "freeTrial": "Dùng Thử Miễn Phí",
    "restorePurchase": "Khôi Phục Mua Hàng",
    "subscribeNow": "Đăng Ký Ngay",
    "trialEnded": "Thời gian dùng thử đã kết thúc",
    "add": "Thêm",
    "cancel": "Hủy",
    "save": "Lưu Thay Đổi",
    "clear": "Xóa",
    "clearHistory": "Xóa Lịch Sử",
    "clearFavorites": "Xóa Yêu Thích",
    "delete": "Xóa",
    "replace": "Thay Thế",
    "skip": "Bỏ Qua",
    "start": "Bắt Đầu",
    "end": "Kết Thúc",
    "switch": "Chuyển Đổi",
    "change": "Thay Đổi",
    "info": "Thông Tin",
    "preview": "Xem Trước",
    "loading": "Đang tải...",
    "liveSessions": "Phiên Trực Tiếp",
    "liveNow": "Đang Trực Tiếp",
    "noLiveSessions": "Không có phiên trực tiếp",
    "favourite": "Yêu Thích",
    "history": "Lịch Sử",
    "whoAreYou": "Bạn là ai?",
    "notSelected": "Chưa chọn",
    "getStarted": "Bắt Đầu",
    "welcome": "Chào Mừng",
    "selectFromSaved": "Chọn từ danh sách đã lưu",
    "selectNameProfile": "Chọn tên để cá nhân hóa hồ sơ",
    "asRegisteredByAdmin": "như admin đã đăng ký",
    "givenByAdmin": "được admin cung cấp",
    "minSixChars": "tối thiểu 6 ký tự",
    "toResetPassword": "để đặt lại mật khẩu nếu quên",
    "yourNameAlias": "tên hoặc bí danh của bạn",
    "defaultPassword": "Mật Khẩu Mặc Định",
    "tile": "Ô",
    "wideTile": "Ô Rộng",
    "description": "Mô tả",
    "addPlayer2": "Thêm",
    "addPlayers": "Thêm người chơi",
    "adminAccess": "Quyền quản trị",
    "adminBadge": "ADMIN",
    "backHome": "‹ Trang chủ",
    "browseBtn": "Duyệt",
    "claimMyAccount": "Xác nhận tài khoản",
    "clearBtn": "Xóa",
    "clubLabel": "CLB",
    "clubRatingLabel": "Xếp hạng CLB",
    "clubSchedulerPro": "CLUB Scheduler Pro",
    "connectToClub": "Kết nối CLB",
    "connectToClubBadminton": "🏸 Kết nối CLB",
    "court": "Sân",
    "courtsLabel": "Sân",
    "editPlayerName": "Sửa tên người chơi",
    "emailLabel": "Email",
    "endBtn": "Kết thúc",
    "favouriteBtn": "Yêu thích",
    "findAClub": "Tìm CLB",
    "findYourClub": "Tìm CLB của bạn",
    "globalRatingLabel": "Xếp hạng toàn cầu",
    "goBtn": "Bắt đầu ›",
    "helpGuide": "Trợ giúp & Hướng dẫn",
    "howUsingAppToday": "Hôm nay bạn sử dụng ứng dụng như thế nào?",
    "inProgress": "Đang diễn ra",
    "joinBtn": "Tham gia",
    "joinRequests": "Yêu cầu tham gia",
    "lessOneShuttle": "Ít hơn một cầu mỗi năm",
    "liveBadge": "LIVE",
    "loadingClubs": "— Đang tải CLB… —",
    "lockBtn": "Khóa",
    "markAllWinners": "Vui lòng đánh dấu người thắng cho tất cả trận",
    "markWinner": "Đánh dấu người thắng",
    "modifyPlayers": "Chỉnh sửa người chơi",
    "newBadge": "MỚI",
    "nextRound": "Vòng tiếp theo",
    "pairsLabel": "Cặp",
    "passwordBlank": "Mật khẩu (để trống nếu không đổi)",
    "passwordLabel": "Mật khẩu",
    "player1": "Người chơi 1",
    "player2": "Người chơi 2",
    "playingNow": "Đang chơi",
    "readyBadge": "SẴN SÀNG",
    "refresh": "↻ Làm mới",
    "registerPlayers": "Đăng ký người chơi",
    "removePlayer": "Xóa người chơi",
    "replaceBtn": "Thay thế",
    "resendCode": "Gửi lại mã",
    "resetRoundsOnly": "Chỉ đặt lại vòng đấu",
    "resting": "Nghỉ",
    "round": "Vòng",
    "roundOrganiserDesc": "Điều hành phiên, tính điểm, quản lý người chơi",
    "roundsLabel": "Vòng đấu",
    "saveSet": "Lưu set",
    "searchByClubName": "Tìm theo tên CLB và gửi yêu cầu",
    "selectClub": "— Chọn CLB —",
    "selectClubDelete": "— Chọn CLB để xóa —",
    "selectClubOption": "— Chọn CLB —",
    "sessionStatsLabel": "Thống kê phiên",
    "settings": "Cài đặt",
    "skipBtn": "Bỏ qua",
    "startBtn": "Bắt đầu",
    "startRoundsBtn": "Bắt đầu vòng ›",
    "subFeature1": "✓ Thống kê đầy đủ & lịch sử phiên",
    "subFeature2": "✓ Vòng đấu & tính điểm trực tiếp",
    "subFeature3": "✓ Chế độ tổ chức — điều hành phiên",
    "subFeature4": "✓ Quản lý người chơi & cặp cố định",
    "subFeature5": "✓ Chế độ khán giả — xem điểm trực tiếp",
    "summaryLabel": "Tóm tắt",
    "switchBtn": "Chuyển đổi",
    "sync": "↻ Đồng bộ",
    "unlockBtn": "Mở khóa",
    "useAdminMode": "Dùng chế độ Vault để có toàn quyền quản trị",
    "userBadge": "USER",
    "userID": "ID người dùng",
    "vaultManagerDesc": "Quản trị CLB — người chơi, yêu cầu, quản lý",
    "verifyEmail": "Xác minh email",
    "viewerBadge": "VIEWER",
    "watchLiveDesc": "Xem vòng đấu & điểm số trực tiếp",
    "welcomeTitle": "Chào mừng",
    "notConnected": "Chưa kết nối",
    "setupBadge": "SETUP",
    "memberMsg": "Bạn là thành viên của CLB này."
  },
  "zh": {
    "home": "首页",
    "players": "球员",
    "rounds": "回合",
    "summary": "汇总",
    "language": "语言",
    "fontSize": "字体大小",
    "reset": "重置",
    "resetAll": "重置应用",
    "resetExcept": "仅重置比赛",
    "enterCourts": "输入场地数量",
    "importPlayers": "浏览玩家 ▶",
    "gender": "性别",
    "male": "男",
    "female": "女",
    "import": "导入",
    "enterPlayerName": "输入球员姓名",
    "fixedPairs2": "设置固定搭档（可选）",
    "pround": " 回合",
    "nround": "开始回合 ",
    "endrounds": "结束并进入下一回合 ",
    "endSession": "结束会话",
    "roundno": "回合 ",
    "roundShort": "R",
    "rank": "排名",
    "name": "姓名",
    "wins": "胜利",
    "played": "已比赛",
    "rested": "休息次数",
    "importExample": "姓名,性别\nKari\nBhavani",
    "Timer": "计时器",
    "min": "分钟",
    "selectPlayer1": "选择球员 1",
    "selectPlayer2": "选择球员 2",
    "small": "小",
    "medium": "中",
    "large": "大",
    "maxcourts": "请输入场地数量",
    "sittingOut": "休息中:",
    "courts": "场地",
    "theme": "主题",
    "light": "浅色",
    "dark": "深色",
    "export": "导出",
    "exporthtml": "📄 导出汇总",
    "confirmResetAll": "确定要重置所有内容吗？",
    "confirmResetGames": "确定只重置比赛吗？",
    "endRoundsConfirm": "确定要结束回合吗？",
    "yes": "确定",
    "help": "帮助",
    "statusReady": "状态: 就绪",
    "statusProgress": "状态: 进行中…",
    "minRounds": "热身轮次",
    "roundSettings": "回合设置",
    "competitive": "竞技模式",
    "browsePlayersSub": "从已保存的球员中选择",
    "appTitle": "运动俱乐部调度器",
    "tagline": "羽毛球 & 匹克球",
    "login": "登录",
    "logout": "登出",
    "createAccount": "创建账户",
    "claimAccount": "认领账户",
    "email": "电子邮件",
    "password": "密码",
    "confirmPassword": "确认密码",
    "newPassword": "新密码",
    "confirmNewPassword": "确认新密码",
    "displayName": "显示名称",
    "recoveryKeyword": "恢复关键词",
    "forgotPassword": "忘记密码？",
    "resetPassword": "重置密码",
    "userId": "用户ID",
    "nickname": "昵称",
    "yourEmail": "您的邮箱",
    "myCard": "我的卡片",
    "myClubs": "我的俱乐部",
    "dashboard": "仪表板",
    "fixedPairs": "固定搭档",
    "selectPlayers": "选择球员",
    "startRounds": "开始回合",
    "watchSession": "观看场次",
    "viewer": "观看者",
    "organiser": "组织者",
    "vault": "管理库",
    "chooseMode": "选择模式",
    "howUsingApp": "选择您使用应用的方式",
    "watchLive": "观看实时回合与比分",
    "runSession": "管理场次、记录分数、管理球员",
    "clubAdmin": "俱乐部管理 — 球员、请求、管理",
    "roundOrganiser": "回合组织者",
    "vaultManager": "管理库管理员",
    "myClubsTitle": "我的俱乐部",
    "findClub": "查找俱乐部",
    "joinClub": "加入",
    "leaveClub": "离开",
    "noClubSelected": "未选择俱乐部",
    "createClub": "创建俱乐部",
    "createNewClub": "创建新俱乐部",
    "createYourClub": "创建您的俱乐部",
    "deleteClub": "删除俱乐部",
    "connectClub": "连接",
    "clubManagement": "俱乐部管理",
    "noClubYet": "还没有俱乐部，创建一个开始吧",
    "searchClub": "搜索俱乐部",
    "findRequest": "查找 & 申请",
    "submitRequest": "提交申请",
    "requestSent": "申请已发送！等待管理员批准。",
    "tapConnect": "点击连接",
    "register": "注册",
    "modify": "修改",
    "requests": "请求",
    "playing": "比赛中",
    "onCourtNow": "正在比赛",
    "pendingApproval": "等待批准",
    "playersInClub": "俱乐部球员",
    "tapToEdit": "点击编辑",
    "joinAClub": "加入俱乐部",
    "newClub": "新俱乐部",
    "removeClub": "删除俱乐部",
    "loadingRequests": "加载请求中...",
    "addPlayer": "添加球员",
    "editPlayer": "编辑球员",
    "addRemove": "添加 · 删除",
    "alwaysTogether": "始终搭档",
    "addAtLeast4": "请至少添加4名球员",
    "myProfile": "我的资料",
    "recentMatches": "近期比赛",
    "sessionStats": "场次统计",
    "sessions": "场次",
    "allTimeWins": "历史总胜",
    "allTimeLosses": "历史总负",
    "globalRating": "全球评分",
    "globalPoints": "全球积分",
    "clubRating": "俱乐部评分",
    "clubPoints": "俱乐部积分",
    "thisWeek": "本周",
    "thisMonth": "本月",
    "thisYear": "今年",
    "signInStats": "登录以查看您的统计",
    "trackStats": "追踪您的评分、胜利和比赛历史。",
    "appearance": "外观",
    "tileStyle": "磁贴样式",
    "flat": "平面",
    "glow": "发光",
    "color": "彩色",
    "subscription": "订阅",
    "currentMode": "当前模式",
    "freeTrial": "免费试用",
    "restorePurchase": "恢复购买",
    "subscribeNow": "立即订阅",
    "trialEnded": "免费试用已结束",
    "add": "添加",
    "cancel": "取消",
    "save": "保存更改",
    "clear": "清除",
    "clearHistory": "清除历史",
    "clearFavorites": "清除收藏",
    "delete": "删除",
    "replace": "替换",
    "skip": "跳过",
    "start": "开始",
    "end": "结束",
    "switch": "切换",
    "change": "更改",
    "info": "信息",
    "preview": "预览",
    "loading": "加载中...",
    "liveSessions": "直播场次",
    "liveNow": "正在直播",
    "noLiveSessions": "没有直播场次",
    "favourite": "收藏",
    "history": "历史",
    "whoAreYou": "您是谁？",
    "notSelected": "未选择",
    "getStarted": "开始使用",
    "welcome": "欢迎",
    "selectFromSaved": "从已保存球员中选择",
    "selectNameProfile": "选择名字以个性化您的资料",
    "asRegisteredByAdmin": "管理员注册的名称",
    "givenByAdmin": "管理员提供",
    "minSixChars": "最少6个字符",
    "toResetPassword": "用于重置密码",
    "yourNameAlias": "您的姓名或别名",
    "defaultPassword": "默认密码",
    "tile": "磁贴",
    "wideTile": "宽磁贴",
    "description": "描述",
    "addPlayer2": "添加",
    "addPlayers": "添加球员",
    "adminAccess": "管理员访问",
    "adminBadge": "ADMIN",
    "backHome": "‹ 首页",
    "browseBtn": "浏览",
    "claimMyAccount": "申请账户",
    "clearBtn": "清除",
    "clubLabel": "俱乐部",
    "clubRatingLabel": "俱乐部评分",
    "clubSchedulerPro": "CLUB Scheduler Pro",
    "connectToClub": "连接俱乐部",
    "connectToClubBadminton": "🏸 连接俱乐部",
    "court": "场地",
    "courtsLabel": "场地",
    "editPlayerName": "编辑球员名称",
    "emailLabel": "电子邮件",
    "endBtn": "结束",
    "favouriteBtn": "收藏",
    "findAClub": "查找俱乐部",
    "findYourClub": "找到您的俱乐部",
    "globalRatingLabel": "全球评分",
    "goBtn": "开始 ›",
    "helpGuide": "帮助与指南",
    "howUsingAppToday": "今天您如何使用应用？",
    "inProgress": "进行中",
    "joinBtn": "加入",
    "joinRequests": "加入请求",
    "lessOneShuttle": "每年少于一个羽毛球",
    "liveBadge": "LIVE",
    "loadingClubs": "— 正在加载俱乐部… —",
    "lockBtn": "锁定",
    "markAllWinners": "请为所有比赛标记获胜者",
    "markWinner": "标记获胜者",
    "modifyPlayers": "修改球员",
    "newBadge": "新",
    "nextRound": "下一回合",
    "pairsLabel": "搭档",
    "passwordBlank": "密码（不更改请留空）",
    "passwordLabel": "密码",
    "player1": "球员1",
    "player2": "球员2",
    "playingNow": "正在比赛",
    "readyBadge": "就绪",
    "refresh": "↻ 刷新",
    "registerPlayers": "注册球员",
    "removePlayer": "删除球员",
    "replaceBtn": "替换",
    "resendCode": "重新发送验证码",
    "resetRoundsOnly": "仅重置回合",
    "resting": "休息中",
    "round": "回合",
    "roundOrganiserDesc": "管理场次、记录分数、管理球员",
    "roundsLabel": "回合",
    "saveSet": "保存组合",
    "searchByClubName": "按俱乐部名称搜索并申请",
    "selectClub": "— 选择俱乐部 —",
    "selectClubDelete": "— 选择要删除的俱乐部 —",
    "selectClubOption": "— 选择俱乐部 —",
    "sessionStatsLabel": "场次统计",
    "settings": "设置",
    "skipBtn": "跳过",
    "startBtn": "开始",
    "startRoundsBtn": "开始回合 ›",
    "subFeature1": "✓ 完整统计与场次历史",
    "subFeature2": "✓ 实时回合与计分",
    "subFeature3": "✓ 组织者模式 — 管理场次",
    "subFeature4": "✓ 球员与固定搭档管理",
    "subFeature5": "✓ 观看者模式 — 观看实时分数",
    "summaryLabel": "汇总",
    "switchBtn": "切换",
    "sync": "↻ 同步",
    "unlockBtn": "解锁",
    "useAdminMode": "使用Vault模式获得完整管理权限",
    "userBadge": "USER",
    "userID": "用户ID",
    "vaultManagerDesc": "俱乐部管理 — 球员、请求、管理",
    "verifyEmail": "验证邮箱",
    "viewerBadge": "VIEWER",
    "watchLiveDesc": "观看实时回合与比分",
    "welcomeTitle": "欢迎",
    "notConnected": "未连接",
    "setupBadge": "SETUP",
    "memberMsg": "您是该俱乐部的成员。"
  }
};
